final Map genreIcons = {
  'Action': 'assets/color_cinema_icons/Action.svg',
  'Adventure': 'assets/color_cinema_icons/Binoculars.svg',
  'Animation': 'assets/color_cinema_icons/Animation.svg',
  'Comedy': 'assets/color_cinema_icons/Comedy.svg',
  'Crime': 'assets/color_cinema_icons/Crime.svg',
  'Documentary': 'assets/color_cinema_icons/Documentary.svg',
  'Drama': 'assets/color_cinema_icons/Drama.svg',
  'Family': 'assets/color_cinema_icons/Family.svg',
  'Fantasy': 'assets/color_cinema_icons/Fantasy.svg',
  'History': 'assets/color_cinema_icons/Historical.svg',
  'Horror': 'assets/color_cinema_icons/Horror.svg',
  'Music': 'assets/color_cinema_icons/Music.svg',
  'Science Fiction': 'assets/color_cinema_icons/Sci Fi.svg',
  'TV Movie': 'assets/color_cinema_icons/TV.svg',
  'Thriller': 'assets/color_cinema_icons/Thriller.svg',
  'Mystery': 'assets/color_cinema_icons/Film Noir.svg',
  'Romance': 'assets/color_cinema_icons/Novel.svg',
  'Western': 'assets/color_cinema_icons/Western.svg',
  'War': 'assets/color_cinema_icons/Ticket.svg',
};
